### ISSUE TITLE
views are not always being counted

### ISSUE THREAD

**Issue by propertunist** [AU-Landing-Project/views_counter#3]
i shared a video on G+ and it got 18 +1s (likes on the google+ platform) over about 12 hours or so. i can see in piwik that it had 3 unique pageviews (from users other than me, since piwik doesn't track my activity). the view counter is showing the total views for the video (from users other than me), since i activated view_counter in mid october, is 1. so piwik shows 3 unique views in 12 hours and view counter shows 1 unique view in nearly 1 month!

obviously something isn't working as intended here.

**Comment by beck24** [comment]
yes, I just haven't had a chance to look it at it yet

**Comment by propertunist** [comment]
no problem, i just moved it here so it's easier to track

**Comment by beck24** [comment]
I can't replicate this - I don't think it's a problem with the plugin as-is.  Potentially a problem with another plugin.

![screen shot 2015-12-17 at 10 43 51 pm](https://cloud.githubusercontent.com/assets/738363/11891076/e037c7d4-a50f-11e5-81f3-444fba756cad.png)
![screen shot 2015-12-17 at 10 44 04 pm](https://cloud.githubusercontent.com/assets/738363/11891078/e03ac59c-a50f-11e5-86ba-37359e26f902.png)
![screen shot 2015-12-17 at 10 44 12 pm](https://cloud.githubusercontent.com/assets/738363/11891080/e03b10e2-a50f-11e5-80ae-36975053cb61.png)
![screen shot 2015-12-17 at 10 44 23 pm](https://cloud.githubusercontent.com/assets/738363/11891079/e03acaba-a50f-11e5-9fa4-02cf8ac96ac9.png)
![screen shot 2015-12-17 at 10 44 34 pm](https://cloud.githubusercontent.com/assets/738363/11891077/e038c30a-a50f-11e5-8447-312661ad6aac.png)
